In [1]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder


In [2]:
data= pd.read_csv('car.data')
print(data.head())

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc


In [3]:
X=data[['buying','maint','safety']].values
y=data[['class']]
print(X,y)

[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]       class
0     unacc
1     unacc
2     unacc
3     unacc
4     unacc
...     ...
1723   good
1724  vgood
1725  unacc
1726   good
1727  vgood

[1728 rows x 1 columns]


In [4]:
#converting the data (X)
Le=LabelEncoder()
for i in range (len(X[0])):
    X[:,i]=Le.fit_transform(X[:,i])
    print (X)

[[3 'vhigh' 'low']
 [3 'vhigh' 'med']
 [3 'vhigh' 'high']
 ...
 [1 'low' 'low']
 [1 'low' 'med']
 [1 'low' 'high']]
[[3 3 'low']
 [3 3 'med']
 [3 3 'high']
 ...
 [1 1 'low']
 [1 1 'med']
 [1 1 'high']]
[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [5]:
#converting y
#mapping
label_mapping={'unacc':0,'acc':1,'good':2,'vgood':3}
y['class']=y['class'].map(label_mapping)
y=np.array(y)
print (y)

[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


C:\Users\KIIT\AppData\Local\Temp\ipykernel_28640\723181935.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['class']=y['class'].map(label_mapping)


In [8]:
#create model
knn=neighbors.KNeighborsClassifier(n_neighbors=25,weights='uniform')
#
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
knn.fit(X_train,y_train)
prediction =knn.predict(X_test)
accuracy=metrics.accuracy_score(y_test,prediction)
print("predictions:",prediction)
print("accuracy:",accuracy)

predictions: [0 0 0 0 0 3 0 0 0 1 0 0 3 3 0 0 3 0 0 1 0 1 1 1 2 0 3 2 0 0 1 3 0 0 0 1 1
 0 0 3 0 1 1 1 0 0 0 0 3 0 0 0 1 2 0 2 0 0 1 3 1 0 0 1 0 0 2 0 1 1 0 0 0 0
 0 0 1 1 2 3 0 0 0 2 0 0 0 1 0 1 3 0 3 0 1 0 1 1 0 0 0 1 0 3 1 0 0 1 0 0 1
 1 0 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 3 0 0 1 1 0 0 0 3 0 1 0 0 0 1 3 0 0
 0 0 1 0 1 3 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 1 2 0 1 0 0 0 0 0 0 0
 0 0 1 0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 2 1 0 0 0 1 1 0 1 0 0 1 0 0 0
 0 3 0 1 0 0 0 0 0 0 0 3 0 1 0 3 3 0 0 0 0 0 0 3 0 0 0 2 1 0 0 0 1 0 0 0 0
 2 0 0 0 1 1 0 0 1 1 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 3 0 1 0 0 0 3 1 0 3 0
 1 0 0 1 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 3 3 0 0 0 0 0 3 1 0
 0 0 0 3 0 0 1 1 0 0 3 2 0]
accuracy: 0.7427745664739884


C:\Users\KIIT\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [15]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test.values.argmax(axis=1), prediction.argmax(axis=1)))

AttributeError: 'numpy.ndarray' object has no attribute 'values'