In [1]:
#"C:\Users\KIIT\Downloads\bezdekIris (1).csv"
from sklearn import datasets
import numpy as np
from sklearn import svm
from sklearn.metrics import accuracy_score

In [2]:
iris=datasets.load_iris()
#split it in features and labels
X=iris.data
y=iris.target
print(X,y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [3]:
classes=['Iris Setosa','Iris Versicolour','Iris Virginica']
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [6]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)


In [7]:
model=svm.SVC()
model.fit(X_train,y_train)
print( model)

SVC()


In [8]:
predictions =model.predict(X_test)
acc=accuracy_score(y_test,predictions)
print("predictions:",predictions)
print("actual:",y_test)
print("accuracy:",acc)

predictions: [2 1 2 2 1 1 1 1 1 1 1 2 0 0 0 1 0 0 2 2 1 2 2 0 2 2 0 0 1 0]
actual: [2 1 2 2 1 1 1 1 1 1 2 2 0 0 0 1 0 0 2 2 1 1 2 0 2 2 0 0 2 0]
accuracy: 0.9


In [9]:
for i in range(len(predictions)):
   print(classes[predictions[i]])

Iris Virginica
Iris Versicolour
Iris Virginica
Iris Virginica
Iris Versicolour
Iris Versicolour
Iris Versicolour
Iris Versicolour
Iris Versicolour
Iris Versicolour
Iris Versicolour
Iris Virginica
Iris Setosa
Iris Setosa
Iris Setosa
Iris Versicolour
Iris Setosa
Iris Setosa
Iris Virginica
Iris Virginica
Iris Versicolour
Iris Virginica
Iris Virginica
Iris Setosa
Iris Virginica
Iris Virginica
Iris Setosa
Iris Setosa
Iris Versicolour
Iris Setosa


In [10]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test.values.argmax(axis=1), predictions.argmax(axis=1)))

AttributeError: 'numpy.ndarray' object has no attribute 'values'